name: Docker Image CI
on:
  push:
    branches: [ main ]
env:
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup Authentication with gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true  
    - name : Authorize Docker push
      run: gcloud auth configure-docker --quiet 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gcr.io/inspiring-lens-325816/timesheet-rest:${{github.sha}}
    - name : Docker Push
      run : docker push gcr.io/inspiring-lens-325816/timesheet-rest:${{github.sha}}
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: 'hello-cloud-run'
        image: 'gcr.io/inspiring-lens-325816/timesheet-rest:${{github.sha}}'
    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
